name: release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release

      - name: Package artifacts
        run: |
          cp target/release/dwf dwf
          tar -czf dwf-linux-x86_64.tar.gz dwf
          sha256sum dwf-linux-x86_64.tar.gz > dwf-linux-x86_64.tar.gz.sha256

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dwf-linux-x86_64.tar.gz
            dwf-linux-x86_64.tar.gz.sha256
